apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
  namespace: demo-api
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: api-demo
  template:
    metadata: 
      labels: 
        app: api-demo
    spec:
      serviceAccountName: api-user
      containers: 
        - name: api
          image: fcruzg/api-k8s-demo:latest
          ports:
            - containerPort: 3000