apiVersion: v1
kind: Service
metadata:
  name: api-demo-service
  namespace: demo-api
spec:
  selector:
    app: api-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
